// components/Layout.tsx
import Link from "next/link";
import Contact from "./Contact";
import Subscribe from "./Subscribe";
import Home from "./SVGs/HomeSVG";
import { ReactNode, useEffect, useState } from "react";
import { useRouter } from "next/router";
import { useTheme } from "next-themes";
import Sun from "./SVGs/Sun";
import Moon from "./SVGs/Moon";

function HeaderLink({ children, href }: { children: ReactNode; href?: string }) {
	const { pathname } = useRouter();
	const itsAString = typeof children === "string";
	return (
		<div className={`group relative ${itsAString && "top-1"}`}>
			{href ? (
				<a
					className="transition-colors ease-out text-secondary dark:text-secondaryDark group-hover:text-primary dark:group-hover:text-primaryDark outline-none focus:text-primary"
					href={href}
				>
					{children}
				</a>
			) : (
				<Link href={itsAString ? `/${children.toLowerCase()}` : "/"}>
					<a className="ease-out block text-secondary dark:text-secondaryDark transition-colors group-hover:text-primary dark:group-hover:text-primaryDark cursor-pointer outline-none focus:text-primary">
						{children}
					</a>
				</Link>
			)}
			{itsAString && (
				<div className="w-full bg-primary dark:bg-primaryDark h-0.5 scale-x-0 group-hover:scale-x-100 transition-transform origin-left duration-500 group-hover:duration-300" />
			)}
		</div>
	);
}

export default function Layout({ children }: { children: ReactNode }) {
	const [mounted, setMounted] = useState(false);
	const { theme, setTheme } = useTheme();

	// When mounted on client, now we can show the icon
	useEffect(() => setMounted(true), []);

	const router = useRouter();

	if (router.pathname.includes("coriolis")) {
		return <div>{children}</div>;
	}

	return (
		<div className="min-h-screen flex flex-col">
			<header
				id="top"
				className="flex text-lg static sm:sticky w-full h-10 top-0 left-0 z-20 justify-between font-semibold backdrop-opacity-80 py-8 px-2 md:px-8 items-center bg-white dark:bg-opacity-100 dark:bg-slate-900 bg-opacity-50"
			>
				<div className="flex items-center">
					<HeaderLink>
						<Home />

						{/* <div className="w-10 h-10 group"> */}

						{/* <img
								src="/dark_house_filled.PNG"
								className={`object-contain opacity-0 group-hover:opacity-100 ${
									router.pathname === "/" && "opacity-100"
								} absolute transition-opacity`}
							/>
							<img src="/dark_house_outline.PNG" className="object-contain" /> */}
						{/* </div> */}
					</HeaderLink>
					<button
						onClick={() => setTheme(theme === "light" ? "dark" : "light")}
						className="w-8 ml-8 text-secondary dark:text-secondaryDark hover:text-primary dark:hover:text-primaryDark outline-none border-current rounded-full relative"
					>
						{/* <div className="w-8 h-8 group"> */}
						{!mounted ? null : theme === "light" ? (
							// <>
							// 	<img
							// 		src="/sun_filled.PNG"
							// 		className="object-contain opacity-0 group-hover:opacity-100 absolute transition-opacity"
							// 	/>
							// 	<img src="/sun_outline.PNG" className="object-contain" />
							// </>
							<Sun />
						) : (
							<Moon />
						)}
						{/* </div> */}
					</button>
				</div>
				<div className="divide-x-8 flex items-center md:divide-x-[2rem] divide-transparent">
					<HeaderLink>About</HeaderLink>
					<HeaderLink>Work</HeaderLink>
					<HeaderLink>Blog</HeaderLink>
					<HeaderLink href="#contact">Contact</HeaderLink>
				</div>
			</header>
			<main className="flex-1">{children}</main>

			<footer className="mt-auto flex text-lg flex-col sm:flex-row justify-evenly py-6 px-20 items-center">
				<Contact />
				<Subscribe />
			</footer>
		</div>
	);
}

// src/routes/__layout.svelte
<script>
	import SvelteTheme from "svelte-themes/SvelteTheme.svelte";

	import Subscribe from "../lib/components/Subscribe.svelte";

	import "../app.css";
	import "../marquee.css";
	import Contact from "../lib/components/Contact.svelte";
	import HeaderLink from "../lib/components/HeaderLink.svelte";

	// import themeStore, { setTheme } from "svelte-themes";
	import Sun from "../lib/components/svgs/Sun.svelte";
	import Moon from "../lib/components/svgs/Moon.svelte";
	import Home from "../lib/components/svgs/Home.svelte";
	import { onMount } from "svelte";
	import Toast from "$lib/components/Toast.svelte";

	// let mounted = false;
	// onMount(() => {
	// 	mounted = true;
	// });

	// function updateTheme() {
	// 	setTheme($themeStore.theme === "light" ? "dark" : "light");
	// }
</script>

<!-- <SvelteTheme attribute="class" /> -->

<svelte:head>
	<!-- <link
		href="https://fonts.googleapis.com/css2?family=Merriweather&family=Merriweather+Sans:wght@500;800&display=swap&text=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-%3D%21%40%23%24%25%5E%26*%28%29_%2B%5B%5D%5C%7B%7D%7C%3B%27%3A%22%3C%3E%3F%2C.%2F"
		rel="stylesheet"
	/>
	<noscript>
		<link
			href="https://fonts.googleapis.com/css2?family=Merriweather&family=Merriweather+Sans:wght@500;800&display=swap&text=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-%3D%21%40%23%24%25%5E%26*%28%29_%2B%5B%5D%5C%7B%7D%7C%3B%27%3A%22%3C%3E%3F%2C.%2F"
			rel="stylesheet"
		/>
	</noscript> -->

	<meta property="og:type" content="website" />
	<meta property="og:locale" content="en_CA" />
	<meta property="og:url" content="https://www.conorbarnes.com" />
	<meta property="og:site_name" content="Conor Barnes" />
	<meta property="og:image" content="https://conorbarnes.com/images/the-painter.png" />

	<meta property="twitter:card" content="summary_large_image" />
	<meta property="twitter:handle" content="@ideopunk" />
	<meta property="twitter:site" content="@ideopunk" />
</svelte:head>

<div class="min-h-screen  dark:bg-slate-900  flex flex-col">
	<header
		id="top"
		class="flex text-lg static sm:sticky w-full h-10 top-0 left-0 z-20 justify-between font-semibold backdrop-opacity-80 py-8 px-2 md:px-8 items-center bg-white dark:bg-opacity-100 dark:bg-slate-900 bg-opacity-50"
	>
		<div class="flex items-center">
			<HeaderLink>
				<h1 class="italic text-xl lg:ml-4">Conor Barnes</h1>
			</HeaderLink>
			<!-- <button
				aria-label="Toggle Theme"
				name="Toggle Theme"
				on:click={updateTheme}
				tabindex="0"
				class="w-8 ml-8 group border-current relative  text-secondary dark:text-secondaryDark transition-colors
				hover:text-primary dark:hover:text-primaryDark focus:text-primary dark:focus:text-primaryDark
				 outline-current"
			>
				{#if mounted && $themeStore.theme === "dark"}
					<Moon />
				{:else if mounted}
					<Sun />
				{/if}
			</button> -->
		</div>
		<div class="divide-x-8 flex items-center md:divide-x-[2rem] divide-transparent">
			<HeaderLink text="About" />
			<HeaderLink text="Work" />
			<HeaderLink text="Blog" />
			<HeaderLink href="/rss.xml" text="RSS" />
		</div>
	</header>
	<main class="flex-1">
		<slot />
	</main>

	<footer class="mt-auto flex text-lg flex-col lg:flex-row justify-evenly py-6 px-20 items-center">
		<Contact />
		<Subscribe />
	</footer>

	<Toast />
</div>
