// src/lib/components/Date.svelte
<script>
	export let dateString = "";
	let parsedDate = new Date(dateString);
	let date = `${parsedDate.toLocaleDateString(["en-CA"], {
		month: "short",
		day: "numeric",
		year: "numeric"
	})}`;

	$: {
		console.log(date);
	}
</script>

<time class="text-sm md:text-base font-light" dateTime={dateString}>
	{date}
</time>

// components/Date.tsx
export default function DateComponent({ dateString }: { dateString: string }) {
	const parsedDate = new Date(dateString);
	const date = `${parsedDate.toLocaleDateString(["en-CA"], {
		month: "short",
		day: "numeric",
		year: "numeric",
	})}`;

	return (
		<time className="text-sm md:text-base font-light" dateTime={dateString}>
			{date}
		</time>
	);
}
