// src/routes/blog/index.svelte
<script context="module" lang="ts">
	export const load = async ({ fetch }: { fetch: any }) => {
		const posts = await fetch("/api/posts.json");
		const allPosts: Post[] = await posts.json();
		return {
			props: { posts: allPosts }
		};
	};
</script>

<script lang="ts">
	import PostPreview from "../../lib/components/PostPreview.svelte";
	import Subscribe from "../../lib/components/Subscribe.svelte";

	export let posts: Post[];
</script>

<svelte:head>
	<title>Blog | Conor Barnes</title>
	<meta name="description" content="Fire Diamonds" />
	<meta property="og:title" content="Blog | Conor Barnes" />
	<meta property="og:description" content="Fire Diamonds" />
</svelte:head>

<section class="mt-8">
	<div class="flex justify-center">
		<ul class="flex-[5] m-4 mt-0 sm:mt-4 py-0 px-2 sm:py-4 sm:px-16 flex flex-col">
			{#each posts as post}
				<PostPreview
					path={post.path}
					date={post.meta.date}
					title={post.meta.title}
					preview={post.meta.preview}
				/>
			{/each}
		</ul>
		<div class="hidden sm:flex flex-col p-4 m-4 flex-1">
			<a
				href="/rss.xml"
				sveltekit:prefetch
				class="ease-out block text-secondary dark:text-secondaryDark transition-colors
	group-hover:text-primary dark:group-hover:text-primaryDark
	focus:text-primary dark:focus:text-primaryDark outline-inherit text-lg sm:text-3xl"
				><span class="text-black dark:text-white">{"| "}</span>RSS</a
			>
			<!-- <Subscribe side /> -->
		</div>
	</div>
</section>

// pages/blog/index.tsx
import { useState } from "react";
import Head from "next/head";

import { getSortedPostsData, getPostData } from "../../lib/posts";
import Link from "next/link";
import Date from "../../components/Date";
import generateRss from "../../lib/rss";
import fs from "fs";
import SubscriptionBox from "../../components/Subscribe";
import { GetStaticProps } from "next";
import { NextSeo } from "next-seo";

interface PostWithID extends PostData {
	id: string;
}

type Props = { allPostsData: PostWithID[] };

// generating rss here as side-effect
export const getStaticProps: GetStaticProps<Props, {}> = async () => {
	const allPostsData = getSortedPostsData("blogposts");
	// const allArticlesData = getSortedPostsData("published-writing");

	// const allPostsText = await Promise.all(
	// 	allPostsData.map(async (post) => getPostData(post.id, "blogposts"))
	// );

	// SIDE EFFECT!!
	const rss = generateRss(allPostsData);
	fs.writeFileSync("./public/rss.xml", rss);

	return { props: { allPostsData } };
};

function PostPreview({ id, date, title, status, preview }: PostWithID) {
	return (
		<Link href={`/blog/${id}`}>
			<a className="h-full w-full ">
				<li className="group  pt-6 border-b-2 p-2">
					<h3 className="text-lg group-hover:text-secondary dark:group-hover:text-secondaryDark transition-colors sm:text-3xl">
						{title}
					</h3>

					<div
						className={`flex justify-between mb-4 group-hover:text-secondary dark:group-hover:text-secondaryDark transition-colors flex-col`}
					>
						<Date dateString={date} />
					</div>
					<p className="mt-4 mb-2 group-hover:text-secondary dark:group-hover:text-secondaryDark transition-colors">
						{preview}
					</p>
				</li>
			</a>
		</Link>
	);
}

export default function blog({ allPostsData }: { allPostsData: PostWithID[] }) {
	return (
		<section className="mt-8">
			<NextSeo
				title="Blog"
				description="Fire Diamonds"
				openGraph={{ title: "Blog", description: "Fire Diamonds" }}
			/>
			<div className="flex justify-center">
				<ul className="flex-[5] m-4 mt-0 sm:mt-4 py-0 px-2 sm:py-4 sm:px-16 flex flex-col">
					{allPostsData.map(({ id, date, title, status, preview }) => (
						<PostPreview
							id={id}
							key={id}
							date={date}
							title={title}
							status={status}
							preview={preview}
						/>
					))}
				</ul>
				<div className="hidden sm:flex flex-col p-4 m-4 flex-1">
					<SubscriptionBox />
				</div>
			</div>
		</section>
	);
}
