// components/Contact.tsx
import { useState, useEffect } from "react";
import Copy from "./SVGs/CopySVG";

function Linky({ text, href }: { text: string; href: string }) {
	return (
		<a
			href={href}
			className="mb-3 transition ease-out hover:pl-4 hover:text-black w-1/2 text-left"
			target="_blank"
			rel="noopener noreferrer"
		>
			{text}
		</a>
	);
}

export default function ContactForm() {
	const [toast, setToast] = useState(false);

	const handleClick = async () => {
		await navigator.clipboard.writeText("conorbarnes93@gmail.com");
		setToast(true);
	};

	useEffect(() => {
		function byebye() {
			setToast(false);
		}

		let timeout;
		toast ? (timeout = setTimeout(byebye, 1000)) : null;

		return () => clearTimeout(timeout);
	}, [toast]);

	return (
		<div
			className="flex sm:flex-col flex-wrap sm:flex-nowrap justify-start h-24 sm:h-44 w-full sm:w-1/2"
			id="contact"
		>
			<div className="flex items-start sm:items-center relative w-1/2 text-left">
				<div className="absolute -left-8" onClick={handleClick}>
					<Copy />
				</div>

				<Linky text="Email" href="mailto:conorbarnes93@gmail.com" />
			</div>
			<Linky text="Twitter" href="https://www.twitter.com/ideopunk" />
			<Linky text="GitHub" href="https://github.com/ideopunk" />
			<Linky text="LinkedIn" href="https://www.linkedin.com/in/conor-barnes-b49833206/" />

			{toast && (
				<p className="toast mb-3 transition ease-out hover:pl-4 hover:text-black w-1/2 text-left text-primary">
					Copied
				</p>
			)}
		</div>
	);
}

// src/lib/components/Contact.svelte
<script>

	import ContactLink from "./ContactLink.svelte";
	import Copy from "./svgs/Copy.svelte";
	import { notifications } from "../funcs/notification";

	async function handleClick() {
		await navigator.clipboard.writeText("conorbarnes93@gmail.com");
		notifications.send("Email address copied!");
	}
</script>

<!-- class=" border-black transition-colors flex lg:flex-col justify-center mr-6 lg:mr-8  w-52  " -->

<div
	class=" border-black transition-colors flex  justify-center mr-6  w-52  "
	id="contact"
>
	<div class="flex   w-1/2 lg:w-full">
		<div class="flex justify-end items-start   lg:w-1/2 px-2">
			<button class="" on:click={handleClick}>
				<Copy />
			</button>
		</div>
		<div class="  lg:w-1/2 px-2">
			<ContactLink text="Email" href="mailto:conorbarnes93@gmail.com" />
			<ContactLink text="Twitter            " href="https://www.twitter.com/ideopunk" />
		</div>
	</div>

	<div class="flex   w-1/2 lg:w-full">
		<div class="order-last   lg:w-1/2 px-2">
			<ContactLink text="GitHub" href="https://github.com/ideopunk" />
			<ContactLink text="LinkedIn" href="https://www.linkedin.com/in/conor-barnes-b49833206/" />
		</div>
		<div class="order-1   lg:w-1/2 px-2" />
	</div>
</div>
